### ISSUE TITLE
Update state from event listener in useEffect

### ISSUE THREAD

**Issue by gtanczyk** [dai-shi/react-tracked#54]
Am I allowed to update state from event listener ?
```
    useEffect(() => {
        window.addEventListener("keydown", () => {
             updateState("something);
         });
         return () => window.removeEventListener("keydown", listener);
    }, [])
```

I'm asking this question, because it seems that doing it this way, will trigger full update on all hooks created with `useSelector`.

ps. Please let me know if full blown codesandbox example is needed

**Comment by dai-shi** [comment]
> Am I allowed to update state from event listener ?

Yes.

> because it seems that doing it this way, will trigger full update on all hooks created with useSelector.

Is it different if you update in some other ways?
Maybe the discussion in #50 is related.

A full codesandbox example would be helpful.

**Comment by gtanczyk** [comment]
Sandbox example: https://codesandbox.io/s/compassionate-shape-3zijg?file=/src/App.js

> Is it different if you update in some other ways?

Yes, it works as expected, when I'm using for example onClick directly from React. You can see this on the example.

Thanks!

**Comment by dai-shi** [comment]
Thanks for the example. That helps!
So, with just a quick trial, it behaves unexpectedly with v1.4.0. v1.2.0 and v2.0.0-alpha.4 works fine.
It's likely a bug (or a limitation that can't be solved) in v1.4.0 (actually v1.3.0 specifically).

`unstable_batchedUpdates` seems to fix the behavior: https://codesandbox.io/s/ancient-worker-znwpg
If that's the case, I could add it in the library and release v1.4.1. Yeah, maybe I should.

**Comment by gtanczyk** [comment]
The problem still exists, when in the example I commented out the `unstable_batchedUpdates` and bumped `react-tracked` to `v2.0.0-alpha.4`

**Comment by dai-shi** [comment]
Would you check this please? https://codesandbox.io/s/dark-resonance-x3l6e?file=/src/state.js
v2 has some breaking changes.

**Comment by gtanczyk** [comment]
`1.2.0` in fact works as expected.
I can't make it work `2.0.0-alpha.4` (`r.createMutableSource is not a function`)

**Comment by gtanczyk** [comment]
Works on `2.0.0-alpha4`.

Thanks a lot! :)

**Comment by dai-shi** [comment]
As I wrote roughly in #50, v1.2.0 is the good one, especially in Legacy Mode.
v1.3.0 (and v1.4.0) is a workaround for the warning by React 16.13, and I hope to obsolete them with v2 with `useMutableSource`.

Anyway, updating state in event listeners is a valid use case, and there's a bug in v1.4.0. I will release v1.4.1 later.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-tracked/v/1.4.1

Thanks for your reporting!
